### ISSUE TITLE
Menu dropdowns

### ISSUE THREAD

**Issue by ryelle** [ryelle/Andromeda#2]

**Comment by melchoyce** [comment]
![screen shot 2015-05-04 at 9 54 59 pm](https://cloud.githubusercontent.com/assets/2846578/7465942/4d95f212-f2a8-11e4-8cbf-dd0678cec1f6.png)

**Comment by melchoyce** [comment]
I think the dashes are okay for grandchild pages.

**Comment by melchoyce** [comment]
```
#primary-menu .sub-menu {
  margin: 20px 0px 0px;
  padding: 5px 0px 10px;
}

#primary-menu ul li a {
  font-size: 14px;
  margin: 7px 0px;
}
```

**Comment by melchoyce** [comment]
(Though that specific css makes the sub menu unhoverable, whoops)

**Comment by ryelle** [comment]
Updated on the site, but since I couldn't use the exact CSS you gave me, can you double check?

**Comment by melchoyce** [comment]
Looks good. Can we bump up the li margins to 10px 0?

**Comment by melchoyce** [comment]
Though maybe 5px top margin on the first li.

**Comment by ryelle** [comment]
@melchoyce All good?
