### ISSUE TITLE
Posts without featured images

### ISSUE THREAD

**Issue by ryelle** [ryelle/Andromeda#3]

**Comment by melchoyce** [comment]
I was leaning against it at first, but look at the demo set up, I think we'll need to put in some sort of placeholder. I'll work on designing one.

**Comment by melchoyce** [comment]
Maybe just super simple: #999 bg, white icon:

![screen shot 2015-05-04 at 8 36 26 pm](https://cloud.githubusercontent.com/assets/2846578/7465395/5429369e-f29d-11e4-8706-178671e7cb32.png)

Worth doing a different icon based on post format? So:

Text: `fa-pencil` or maybe `fa-align-left`?
Image: `fa-camera`
Gallery: `fa-image`
Audio: `fa-music`
Video: `fa-video-camera`
Quote: `fa-quote-left`
Link: `fa-link`

etc.

**Comment by melchoyce** [comment]
Can we downsize icon to fa-3x?
