### ISSUE TITLE
Better labels/descrips for customizer settings

### ISSUE THREAD

**Issue by ryelle** [ryelle/Andromeda#5]
https://cloudup.com/cuOI3lGfiWP

**Comment by melchoyce** [comment]
Maybe:

> **Number of recent posts on the homepage**
> _We recommend 3_

Is "we recommend" too informal?

> **First/Second/Third Homepage Featured Category**

Maybe "post category?"

> **Copyright**
> _Appears in the footer_

**Comment by ryelle** [comment]
I think what we have for Front Page Settings is good:
![screen shot 2015-10-04 at 4 58 29 pm](https://cloud.githubusercontent.com/assets/541093/10270224/2a4cde90-6ab9-11e5-8a9d-3edd087facc4.png)

But we could use a description for the Colors section -- what the 3 colors do (bg and text are pretty obvious, highlight is the link color) and that we'll alter the text color to be within readable contrast ratios.

**Comment by ryelle** [comment]
![screen shot 2016-01-09 at 1 02 16 pm](https://cloud.githubusercontent.com/assets/541093/12217523/437cdb2c-b6d1-11e5-89f0-c5b377e87a42.png)

I feel like Background Color is obvious.

Text Color is obvious, but needs a note that you can't make hideously unreadable text (if you try to put white text on a white background, it resets it to 6d6d6d).

Highlight Color probably should get a sentence... "This is used for your links, and anywhere that needs a touch of color"? Maybe it should be called "Accent Color"?

**Comment by melchoyce** [comment]
I think your text color description makes sense (though `adjusted` has a typo).

I think "Accent Color" works better and... is maybe self-explanatory? We can run the color scheme builder by some folks before launching.

**Comment by ryelle** [comment]
Changed to "Accent" & fixed the typo. Going to close this for now & open another for testing the color scheme section -- since #27 would also benefit from this testing.
